server:
  port: 3000
spring:
  datasource:
    url: jdbc:h2:mem:myapp-test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
