server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://192.168.0.5:3306/mydb
    username: myuser
    password: dbsdud12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  boot:
    admin:
      client:
        instance:
          name: My Spring Boot App (Todo)
        url: http://192.168.0.3:8888
management:
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"